export const PUBLICATIONS = {
  GET_PUBLICATIONS: 'GET_PUBLICATIONS',
  CHANGE_ORDER: 'CHANGE_ORDER',
  CHANGE_AUTHOR_QUERY: 'CHANGE_AUTHOR_QUERY'
};

export const AUTHORS = {
  GET_AUTHORS: 'GET_AUTHORS'
};

export const PUBLICATION = {
  GET_PUBLICATION: 'GET_PUBLICATION',
  GET_AUTHOR_NAME: 'GET_AUTHOR_NAME',
  CLEAR_PUBLICATION: 'CLEAR_PUBLICATION'
};

export const LOADER = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER'
};
